# Configuration of NoSnips services
#
# Dec. 2019, A. Dominik
#
title = "NoSnips services config"

[local]
# satellite = false    false for the main system; if true, only hotword
#                      detectiion and auidio I/O will be started
# name = "default"     name of satellite/room
# base_directory = ""  installation directory (/..../ADoNoSnips)
satellite = false
siteId = "default"
base_directory = "/home/andreas/Snips/Dev/ADoSnipsQnD/NoSnips"
work_dir = "/tmp"


[mqtt]
host = localhost
port = 8883
susbcribe = mosquitto_sub
publish = mosquitto_pub


[hotword]
# start = true          start hotword service
# binary = "Snowboy/bin/hotword"     path to the hotword detector
# model_path = "Snowboy/resources"   path to the hotword models
# model = "computer.pmdl"            name of hotword model
# sensitivity = 0.5
# session_timeout = 60               60 secs after hotword recognition
#                                    hotword detector is restarted because of
#                                    timeout
start = true
daemon = "Hotword/hotword.daemon"
binary = "Snowboy/bin/hotword.py"
model_path = "Snowboy/resources"
model = "computer.pmdl"
sensitivity = 0.5


[record]
# start = true     start the service to record commands
start = true

[say]
# start = true     start the service to utter text
start = true

[STT]
# start = true     start the speech-to-text (aka ASR) service
start = true

[NLU]
# start = true     start the natural language understanding service
#                  to identify intents and extract slot values
start = true


[session]
# The session manager ...
start = true
daemon = "Session/session.daemon"
session_timeout = 60
